# ardzy_pins.xdc - every usable FPGA pin of the Antminer S9 control board (XC7Z010-CLG400)
# Generated by scripts/make_pins.py from the board schematic. Uncomment the lines you use,
# and name your top-level ports the same (or edit the names here).
# All FPGA (PL) pins on this board are 3.3 V: IOSTANDARD LVCMOS33. Never apply 5 V.

# ---- hash-board connectors J1..J9: jN[0]=pin 5, jN[1]=pin 11, jN[2]=pin 12, jN[3]=pin 15
#      (pin 3 = SDA, pin 4 = SCL, pin 16 = 3.3 V, pins 1,2,9,10,13,14 = GND)
#set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {j1[0]}] ;# J1 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVCMOS33} [get_ports {j1[1]}] ;# J1 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {j1[2]}] ;# J1 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {j1[3]}] ;# J1 pin 15 (RST)

#set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports {j2[0]}] ;# J2 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {j2[1]}] ;# J2 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {j2[2]}] ;# J2 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports {j2[3]}] ;# J2 pin 15 (RST)

#set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {j3[0]}] ;# J3 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {j3[1]}] ;# J3 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {j3[2]}] ;# J3 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {j3[3]}] ;# J3 pin 15 (RST)

#set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {j4[0]}] ;# J4 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {j4[1]}] ;# J4 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports {j4[2]}] ;# J4 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {j4[3]}] ;# J4 pin 15 (RST)

#set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {j5[0]}] ;# J5 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {j5[1]}] ;# J5 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports {j5[2]}] ;# J5 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {j5[3]}] ;# J5 pin 15 (RST)

#set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {j6[0]}] ;# J6 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {j6[1]}] ;# J6 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {j6[2]}] ;# J6 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports {j6[3]}] ;# J6 pin 15 (RST)

#set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {j7[0]}] ;# J7 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {j7[1]}] ;# J7 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {j7[2]}] ;# J7 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports {j7[3]}] ;# J7 pin 15 (RST)

#set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {j8[0]}] ;# J8 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {j8[1]}] ;# J8 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports {j8[2]}] ;# J8 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {j8[3]}] ;# J8 pin 15 (RST)

#set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {j9[0]}] ;# J9 pin 5  (PLUG)
#set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {j9[1]}] ;# J9 pin 11 (TXD)
#set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {j9[2]}] ;# J9 pin 12 (RXD)
#set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {j9[3]}] ;# J9 pin 15 (RST)

# ---- on-board LEDs (ACTIVE LOW: drive 0 to light), fans, I2C, board ID, test point
#set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports {leds[0]}] ;# on-board LED, ACTIVE LOW (0 = on)
#set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {leds[1]}] ;# on-board LED, ACTIVE LOW (0 = on)
#set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports {leds[2]}] ;# on-board LED, ACTIVE LOW (0 = on)
#set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {leds[3]}] ;# on-board LED, ACTIVE LOW (0 = on)
#set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {fan_pwm}] ;# PWM to pin 4 of all 6 fan headers (shared)
#set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {fan_tach[0]}] ;# FAN1 speed (pin 3), 10k pull-up
#set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {fan_tach[1]}] ;# FAN2 speed (pin 3), 10k pull-up
#set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {fan_tach[2]}] ;# FAN3 speed (pin 3), 10k pull-up
#set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {fan_tach[3]}] ;# FAN4 speed (pin 3), 10k pull-up
#set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {fan_tach[4]}] ;# FAN5 speed (pin 3), 10k pull-up
#set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports {fan_tach[5]}] ;# FAN6 speed (pin 3), 10k pull-up
#set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {i2c1_scl}] ;# SCL on J1..J8 pin 4, 1k pull-up
#set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {i2c1_sda}] ;# SDA on J1..J8 pin 3, 1k pull-up
#set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {i2c2_scl}] ;# SCL on J9 pin 4, 1k pull-up
#set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {i2c2_sda}] ;# SDA on J9 pin 3, 1k pull-up
#set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {board_id[0]}] ;# board version strap (input)
#set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {board_id[1]}] ;# board version strap (input)
#set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {board_id[2]}] ;# board version strap (input)
#set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports {board_id[3]}] ;# board version strap (input)
#set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {tp1}] ;# test point TP1 "CLOCK_OUT" (handy scope probe pin)

# LEDs: gentle drive
#set_property -dict {DRIVE 8 SLEW SLOW} [get_ports {leds[*]}]
# I2C lines need open-drain style logic (IOBUF), the board already has 1k pull-ups.
