/* Ardzy - Code view data: the API reference (searchable, also used for autocomplete) and the snippets.
   Languages: ino (Arduino C++), py (Python on the ARM), v (Verilog), c (C on the ARM). */

// [name, signature, what it does, language, example]
const CODE_REF = [
  // ---------------- Arduino: pins
  ['pinMode', 'pinMode(pin, mode)', 'Sets a pin as OUTPUT, INPUT or INPUT_PULLUP. Connector pins are J1_5 .. J9_15 (4 per connector).', 'ino', 'pinMode(J3_5, OUTPUT);'],
  ['digitalWrite', 'digitalWrite(pin, HIGH / LOW)', 'Drives an output pin to 3.3 V (HIGH) or 0 V (LOW).', 'ino', 'digitalWrite(LED0, HIGH);'],
  ['digitalRead', 'int digitalRead(pin)', 'Reads a pin: HIGH or LOW. Buttons BUTTON_IP / BUTTON_RESET read LOW while pressed.', 'ino', 'if (digitalRead(BUTTON_IP) == LOW) beep();'],
  ['analogWrite', 'analogWrite(pin, value)', 'PWM in the FPGA: 0 = off .. 255 = always on (8 bits unless analogWriteResolution). 1000 Hz unless analogWriteFrequency.', 'ino', 'analogWrite(LED1, 128);   // half brightness'],
  ['analogWriteFrequency', 'analogWriteFrequency(pin, hz)', 'PWM frequency of one pin (default 1000 Hz). Motors like 20000, LEDs 1000.', 'ino', 'analogWriteFrequency(J4_5, 20000);'],
  ['analogWriteResolution', 'analogWriteResolution(bits)', 'Range of analogWrite: 8 bits = 0..255 (default), 10 bits = 0..1023, up to 16.', 'ino', 'analogWriteResolution(10);'],
  ['analogRead', 'int analogRead(A0 .. A6)', 'There are no analog pins on the connectors: A0 is the chip temperature, A1..A6 the supply voltages (XADC). 10 bits unless analogReadResolution.', 'ino', 'int t = analogRead(A0);'],
  ['analogReadResolution', 'analogReadResolution(bits)', 'Range of analogRead (default 10 bits, like an Uno).', 'ino', 'analogReadResolution(12);'],
  ['pulseIn', 'unsigned long pulseIn(pin, HIGH / LOW, timeout_us)', 'Length of the next pulse on a pin in microseconds (0 on timeout).', 'ino', 'unsigned long us = pulseIn(J5_11, HIGH, 30000);'],
  ['attachInterrupt', 'attachInterrupt(pin, function, RISING / FALLING / CHANGE)', 'Calls your function on an edge. Runs in its own thread: keep it short, use volatile variables.', 'ino', 'attachInterrupt(J2_5, onEdge, RISING);'],
  ['detachInterrupt', 'detachInterrupt(pin)', 'Stops calling the interrupt function of a pin.', 'ino', 'detachInterrupt(J2_5);'],
  ['tone', 'tone(pin, hz, ms)', 'A square wave on a pin (a passive buzzer or speaker with 100 ohm in series). Without ms it plays until noTone.', 'ino', 'tone(J1_5, 440, 200);'],
  ['noTone', 'noTone(pin)', 'Stops a tone.', 'ino', 'noTone(J1_5);'],
  ['shiftOut', 'shiftOut(dataPin, clockPin, MSBFIRST / LSBFIRST, value)', 'Sends 8 bits on a data and a clock pin (74HC595 shift registers).', 'ino', 'shiftOut(J6_5, J6_11, MSBFIRST, 0xA5);'],
  ['shiftIn', 'uint8_t shiftIn(dataPin, clockPin, bitOrder)', 'Reads 8 bits with a clock pin (74HC165).', 'ino', 'uint8_t b = shiftIn(J6_12, J6_11, MSBFIRST);'],
  // ---------------- Arduino: time
  ['millis', 'unsigned long millis()', 'Milliseconds since the program started. Use it for timers that do not stop the program.', 'ino', 'if (millis() - last >= 500) { last = millis(); ... }'],
  ['micros', 'unsigned long micros()', 'Microseconds since the program started.', 'ino', 'unsigned long t0 = micros();'],
  ['delay', 'delay(ms)', 'Waits. The rest of the program stops meanwhile (a timer with millis() does not).', 'ino', 'delay(1000);'],
  ['delayMicroseconds', 'delayMicroseconds(us)', 'Short exact waits (Linux: very short ones are busy waits).', 'ino', 'delayMicroseconds(10);'],
  // ---------------- Arduino: math, text
  ['map', 'long map(x, inLow, inHigh, outLow, outHigh)', 'Scales a number from one range to another (whole numbers).', 'ino', 'int pwm = map(t, 40, 80, 0, 255);'],
  ['constrain', 'constrain(x, low, high)', 'Keeps a number inside a range.', 'ino', 'p = constrain(p, 0, 100);'],
  ['random', 'long random(min, max)', 'A random whole number from min to max - 1. randomSeed() changes the series.', 'ino', 'int dice = random(1, 7);'],
  ['String', 'String(value)', 'Text that can grow: + joins, .length(), .toInt(), .indexOf() ...', 'ino', 'String s = "t = " + String(t, 1);'],
  // ---------------- Arduino: Serial
  ['Serial.begin', 'Serial.begin(baud)', 'Starts Serial. On Ardzy Serial is the app\'s Monitor (the speed does not matter).', 'ino', 'Serial.begin(115200);'],
  ['Serial.println', 'Serial.println(value)', 'Prints a line in the Monitor. "name:value" lines draw on the Plotter.', 'ino', 'Serial.println(Ardzy.temperature());'],
  ['Serial.print', 'Serial.print(value)', 'Prints without a new line.', 'ino', 'Serial.print("t = ");'],
  ['Serial.available', 'int Serial.available()', 'How many characters you typed in the Monitor input are waiting.', 'ino', 'while (Serial.available()) { char c = Serial.read(); }'],
  ['Serial.readStringUntil', 'String Serial.readStringUntil(\'\\n\')', 'One line typed in the Monitor.', 'ino', 'String cmd = Serial.readStringUntil(\'\\n\');'],
  ['Serial1', 'Serial1.begin(baud)', 'A real UART made in the FPGA: TX J1 pin 11, RX J1 pin 12 (Serial1.setPins(rx, tx) for others). 3.3 V levels.', 'ino', 'Serial1.begin(9600); Serial1.println("hi");'],
  // ---------------- Arduino: the board
  ['Ardzy.beep', 'Ardzy.beep(ms)', 'The buzzer on the board.', 'ino', 'Ardzy.beep(100);'],
  ['Ardzy.temperature', 'float Ardzy.temperature()', 'Temperature of the Zynq chip in degrees C.', 'ino', 'float t = Ardzy.temperature();'],
  ['Ardzy.voltage', 'float Ardzy.voltage("vccint")', 'A supply voltage measured inside the chip: vccint, vccaux, vccbram, vccpint, vccpaux, vccoddr.', 'ino', 'float v = Ardzy.voltage("vccint");'],
  ['Ardzy.fan', 'Ardzy.fan(percent)', 'All 6 fan headers: 0..100 % (PWM), -1 = full speed without PWM.', 'ino', 'Ardzy.fan(40);'],
  ['Ardzy.fanRpm', 'int Ardzy.fanRpm(1..6)', 'Speed of a fan from its tach wire.', 'ino', 'int rpm = Ardzy.fanRpm(1);'],
  ['Ardzy.fpgaClock', 'unsigned long Ardzy.fpgaClock()', 'The FPGA clock FCLK0 in Hz (normally 100 000 000).', 'ino', 'Serial.println(Ardzy.fpgaClock());'],
  ['Ardzy.chipId', 'const char *Ardzy.chipId()', 'The unique Device DNA of this chip (hex).', 'ino', 'Serial.println(Ardzy.chipId());'],
  ['Ardzy.watch', 'Ardzy.watch("name", value)', 'Shows a value live in the app (Watch tab, Plotter) and in the board\'s data logger. Numbers or text.', 'ino', 'Ardzy.watch("speed", speed);'],
  ['Ardzy.pinControlLoaded', 'bool Ardzy.pinControlLoaded()', 'True when the pin-control FPGA design runs (sketches load it by themselves).', 'ino', 'if (!Ardzy.pinControlLoaded()) Serial.println("no pins");'],
  // ---------------- Arduino: libraries
  ['Wire', '#include <Wire.h>  Wire.begin()', 'I2C on bus 1 (pins 3 SDA / 4 SCL of J1..J8); Wire1 = bus 2 on J9. 1 kohm pull-ups on the board.', 'ino', 'Wire.beginTransmission(0x3C); Wire.write(0); Wire.endTransmission();'],
  ['SPI', '#include <SPI.h>  SPI.begin()', 'SPI on J2: CS pin 5 (SS), MOSI pin 11, MISO pin 12, SCK pin 15.', 'ino', 'SPI.beginTransaction(SPISettings(1000000, MSBFIRST, SPI_MODE0));'],
  ['Servo', '#include <Servo.h>  Servo s; s.attach(pin); s.write(deg)', 'Hobby servos, 0..180 degrees. The servo needs its own 5 V supply (GND shared).', 'ino', 's.attach(J5_5); s.write(90);'],
  ['EEPROM', '#include <EEPROM.h>  EEPROM.read(a) / write(a, b)', 'Values kept after power-off (a file on the SD card), 4096 bytes.', 'ino', 'EEPROM.write(0, count);'],
  // ---------------- Arduino: pin names
  ['J1_5 .. J9_15', 'J<n>_5, J<n>_11, J<n>_12, J<n>_15', 'The 36 free FPGA pins: 4 on each connector J1..J9 (pins 5, 11, 12, 15). 3.3 V, about 10 mA each.', 'ino', 'pinMode(J7_12, INPUT_PULLUP);'],
  ['LED0 .. LED3', 'LED0, LED1, LED2, LED3 (LED_BUILTIN = LED0)', 'The 4 small LEDs of the FPGA (D4..D7).', 'ino', 'digitalWrite(LED_BUILTIN, HIGH);'],
  ['LED_GREEN / LED_RED / LED_D2', 'LED_GREEN, LED_RED, LED_D2', 'The status LEDs (ARM pins).', 'ino', 'digitalWrite(LED_RED, HIGH);'],
  ['BUTTON_IP / BUTTON_RESET', 'BUTTON_IP, BUTTON_RESET', 'The two buttons; they read LOW while pressed.', 'ino', 'if (!digitalRead(BUTTON_IP)) ...'],
  ['FAN1_TACH .. FAN_PWM', 'FAN1_TACH .. FAN6_TACH, FAN_PWM', 'Fan speed inputs and the shared fan PWM output.', 'ino', 'analogWrite(FAN_PWM, 100);'],
  // ---------------- Python
  ['MMIO', 'from ardzy import MMIO;  r = MMIO(base)', 'Registers of your FPGA design. ardzy_soc: base 0x41200000, ctrl n at 4*n, status n at 0x80 + 4*n.', 'py', 'r = MMIO(0x41200000)\nr.write(0, 5)\nprint(r.read(0x80))'],
  ['MMIO.read', 'value = r.read(offset)', 'Reads a 32-bit register (offset in bytes).', 'py', 'v = r.read(0x80)'],
  ['MMIO.write', 'r.write(offset, value)', 'Writes a 32-bit register.', 'py', 'r.write(4, 0xFF)'],
  ['peek / poke', 'peek(addr) / poke(addr, value)', 'One register read or write at any physical address.', 'py', 'from ardzy import peek\nprint(hex(peek(0xF8000530)))'],
  ['UIO', 'UIO(name).wait()', 'Interrupts from the FPGA (a device with compatible = "generic-uio").', 'py', 'irq = UIO("my_ip")\nn = irq.wait()'],
  ['led', 'led(name, on=True)', 'Board LED: led("green"), led("red", False), led("ps").', 'py', 'led("green")'],
  ['beep', 'beep(seconds=0.1)', 'The buzzer.', 'py', 'beep(0.2)'],
  ['button', 'button("ip") / button("reset")', 'True while the button is pressed.', 'py', 'if button("ip"): print("pressed")'],
  ['watch', 'watch(name=value, ...)', 'Shows values live in the app (Watch tab, Plotter) and in the board\'s data logger. Numbers and text.', 'py', 'from ardzy import watch\nwatch(speed=speed, state="run")'],
  ['fpga_state', 'fpga_state()', 'The FPGA manager state (operating, unknown, ...).', 'py', 'print(fpga_state())'],
  ['blocks.Bus', 'from blocks import Bus', 'Ready projects: the slot bus at 0x43C0_0000 (slot n = n * 0x1000) and the classes for each block.', 'py', 'from blocks import Bus\nbus = Bus()'],
  // ---------------- Verilog library
  ['ardzy_soc', 'ardzy_soc #(.N_CTRL(n), .N_STAT(m)) u (.clk, .rstn, .ctrl, .status)', 'Clock (100 MHz), reset and registers to the ARM: ctrl[32*n-1:0] written at 0x4120_0000 + 4*n, status read at 0x4120_0080 + 4*n.', 'v', 'ardzy_soc #(.N_CTRL(2), .N_STAT(1)) u_soc (.clk(clk), .rstn(rstn), .ctrl(ctrl), .status(count));'],
  ['ardzy_clock', 'ardzy_clock u (.clk(clk))', 'Only the 100 MHz clock (FCLK0), for designs that do not talk to the ARM.', 'v', 'wire clk; ardzy_clock u_clk (.clk(clk));'],
  ['ardzy_bus', 'ardzy_bus u (.clk, .rstn, .bus_addr, .bus_wdata, .bus_we, .bus_re, .bus_rdata)', 'The slot bus of the Ardzy blocks: 16 slots of 4 KB at 0x43C0_0000 + n * 0x1000.', 'v', 'ardzy_bus u_bus (.clk(clk), .rstn(rstn), .bus_addr(a), .bus_wdata(wd), .bus_we(we), .bus_re(re), .bus_rdata(rd));'],
  ['ardzy_info', 'ardzy_info #(.SLOT(0), .PROJECT("NAME"))', 'Slot with the project id (4 letters) and version: Python checks it before using a design.', 'v', 'ardzy_info #(.SLOT(0), .PROJECT("TEST")) u_info (...);'],
  ['ardzy_gpio', 'ardzy_gpio #(.W1(32), .W2(17))', 'Registers compatible with the Xilinx AXI GPIO.', 'v', ''],
  ['ardzy_dds', 'ardzy_dds #(.SLOT(n))', 'Signal generator: sine/triangle/saw/square, sigma-delta and PWM DAC outputs.', 'v', ''],
  ['ardzy_i2c', 'ardzy_i2c #(.SLOT(n))', 'I2C controller with a command queue.', 'v', ''],
  ['ardzy_spi', 'ardzy_spi #(.SLOT(n))', 'SPI controller (modes 0..3, 1..32 bits, up to 50 MHz).', 'v', ''],
  ['ardzy_quad', 'ardzy_quad #(.SLOT(n), .N(2))', 'Quadrature encoder counters with a glitch filter.', 'v', ''],
  ['ardzy_stepper', 'ardzy_stepper #(.SLOT(n), .N(2))', 'Step / dir generator with acceleration.', 'v', ''],
  ['ardzy_pattern', 'ardzy_pattern #(.SLOT(n), .W(16))', 'Pattern generator: up to 1024 steps on W pins.', 'v', ''],
  ['ardzy_ws2812', 'ardzy_ws2812 #(.SLOT(n))', 'WS2812 / NeoPixel LED strips, up to 1024 LEDs.', 'v', ''],
  ['ardzy_vga', 'ardzy_vga #(.SLOT(n))', 'VGA output with a text and graphics buffer.', 'v', ''],
  ['ardzy_audio', 'ardzy_audio #(.SLOT(n))', 'I2S sound out and in, PDM microphone.', 'v', ''],
  ['ardzy_sensors', 'ardzy_sensors #(.SLOT(n))', 'HC-SR04 distance, NEC IR remote, capacitive touch.', 'v', ''],
  ['ardzy_rv32_system', 'ardzy_rv32_system #(.SLOT(n))', 'A small RISC-V processor (RV32I) with its memory.', 'v', ''],
  ['ardzy_axis_fifo', 'ardzy_axis_fifo #(.W(32), .AW(6))', 'AXI-Stream FIFO (LUT RAM).', 'v', ''],
  ['ardzy_sine_rom', 'ardzy_sine_rom u (.clk, .a(10 bits), .q(16 bits signed))', 'One sine period, 1024 points, 1 clock latency.', 'v', ''],
  ['leds', 'output wire [3:0] leds', 'The 4 FPGA LEDs, ACTIVE LOW (0 = on). Pins come from the project pins file.', 'v', 'assign leds = ~count[26:23];'],
  ['j1 .. j9', 'inout wire [3:0] j1', 'The connector pins: j1[0] = J1 pin 5, j1[1] = pin 11, j1[2] = pin 12, j1[3] = pin 15.', 'v', 'assign j3[0] = pwm;'],
  ['fan_pwm / fan_tach', 'output fan_pwm, input [5:0] fan_tach', 'Fan PWM (shared by the 6 headers) and the 6 tach inputs.', 'v', ''],
  // ---------------- C
  ['mmap /dev/mem', 'open("/dev/mem") + mmap(..., 0x41200000)', 'Registers of your FPGA design from C (the c_program template has it ready).', 'c', 'volatile uint32_t *r = mmap(0, 0x1000, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0x41200000);'],
];

// snippets: [name, language, code]  ("|" marks where the cursor goes)
const CODE_SNIPPETS = [
  ['setup and loop', 'ino', 'void setup() {\n  Serial.begin(115200);\n  |\n}\n\nvoid loop() {\n}\n'],
  ['timer without delay', 'ino', 'static unsigned long last = 0;\nif (millis() - last >= 500) {     // every 500 ms\n  last = millis();\n  |\n}\n'],
  ['button with debounce', 'ino', 'static int stable = HIGH, lastRead = HIGH;\nstatic unsigned long changed = 0;\nint now = digitalRead(BUTTON_IP);\nif (now != lastRead) { changed = millis(); lastRead = now; }\nif (millis() - changed > 30 && now != stable) {\n  stable = now;\n  if (stable == LOW) {      // pressed\n    |\n  }\n}\n'],
  ['fade an LED (PWM)', 'ino', 'for (int b = 0; b <= 255; b += 5) { analogWrite(LED0, b); delay(10); }\nfor (int b = 255; b >= 0; b -= 5) { analogWrite(LED0, b); delay(10); }\n|'],
  ['watch values live', 'ino', 'Ardzy.watch("count", count);\nArdzy.watch("temperature", Ardzy.temperature());\n|'],
  ['plot values', 'ino', 'Serial.print("temp:"); Serial.print(Ardzy.temperature());\nSerial.print(" fan:"); Serial.println(Ardzy.fanRpm(1));\n|'],
  ['fan follows temperature', 'ino', 'float t = Ardzy.temperature();\nint p = constrain(map((long)t, 45, 70, 0, 100), 0, 100);\nArdzy.fan(p);\n|'],
  ['state machine', 'ino', 'enum State { IDLE, RUN, DONE };\nstatic State st = IDLE;\nswitch (st) {\n  case IDLE: if (!digitalRead(BUTTON_IP)) st = RUN; break;\n  case RUN:  |; st = DONE; break;\n  case DONE: st = IDLE; break;\n}\n'],
  ['servo', 'ino', '#include <Servo.h>\nServo servo;\n// in setup():  servo.attach(J5_5);\n// in loop():   servo.write(90);\n|'],
  ['I2C read a register', 'ino', '#include <Wire.h>\nuint8_t readReg(uint8_t dev, uint8_t reg) {\n  Wire.beginTransmission(dev); Wire.write(reg); Wire.endTransmission(false);\n  Wire.requestFrom(dev, (uint8_t)1);\n  return Wire.available() ? Wire.read() : 0;\n}\n|'],
  ['read a command from the Monitor', 'ino', 'if (Serial.available()) {\n  String cmd = Serial.readStringUntil(\'\\n\');\n  cmd.trim();\n  if (cmd == "on") digitalWrite(LED0, HIGH);\n  else if (cmd == "off") digitalWrite(LED0, LOW);\n  |\n}\n'],
  ['program start', 'py', 'import time\nfrom ardzy import MMIO, led, beep\n\nregs = MMIO(0x41200000)      # ardzy_soc: ctrl n at 4*n, status n at 0x80 + 4*n\n\nwhile True:\n    |\n    time.sleep(0.1)\n'],
  ['watch values live (Python)', 'py', 'from ardzy import watch\nwatch(value=value, state="running")     # Watch tab, Plotter, data logger\n|'],
  ['read the FPGA status', 'py', 'value = regs.read(0x80)       # status[0]\nprint("status:", value)\n|'],
  ['plot values (Python)', 'py', 'print("value:%d" % value, flush=True)   # name:value lines draw on the Plotter\n|'],
  ['timed loop', 'py', 'period = 0.05\nnext_t = time.monotonic()\nwhile True:\n    |\n    next_t += period\n    time.sleep(max(0, next_t - time.monotonic()))\n'],
  ['wait for a button', 'py', 'from ardzy import button\nwhile not button("ip"):\n    time.sleep(0.02)\n|'],
  ['save to a CSV file', 'py', 'import csv\nwith open("log.csv", "a", newline="") as f:\n    csv.writer(f).writerow([time.time(), |])\n'],
  ['top with ardzy_soc', 'v', 'module top (\n    output wire [3:0] leds\n);\n    wire clk, rstn;\n    wire [63:0] ctrl;               // 2 registers from the ARM\n    wire [31:0] status;\n    ardzy_soc #(.N_CTRL(2), .N_STAT(1)) u_soc (.clk(clk), .rstn(rstn), .ctrl(ctrl), .status(status));\n    |\n    assign leds = ~ctrl[3:0];          // LEDs are active low\nendmodule\n'],
  ['counter', 'v', 'reg [31:0] count = 32\'d0;\nalways @(posedge clk) count <= count + 1\'b1;\n|'],
  ['clock enable (tick)', 'v', 'reg [26:0] div = 27\'d0;\nreg tick = 1\'b0;                     // one clock long, 1 per second\nalways @(posedge clk) begin\n    tick <= (div == 27\'d99_999_999);\n    div  <= tick ? 27\'d0 : div + 1\'b1;\nend\n|'],
  ['synchronizer + edge', 'v', 'reg [2:0] s = 3\'b000;                // input from a pin: 2 flip-flops against metastability\nalways @(posedge clk) s <= {s[1:0], pin_in};\nwire rise = s[1] & ~s[2];\nwire fall = ~s[1] & s[2];\n|'],
  ['debouncer', 'v', 'reg [19:0] cnt = 20\'d0;\nreg clean = 1\'b1;\nalways @(posedge clk)\n    if (s[1] == clean) cnt <= 20\'d0;\n    else if (cnt == 20\'d999_999) begin clean <= s[1]; cnt <= 20\'d0; end   // stable 10 ms\n    else cnt <= cnt + 1\'b1;\n|'],
  ['PWM', 'v', 'reg [7:0] pcnt = 8\'d0;\nalways @(posedge clk) pcnt <= pcnt + 1\'b1;           // 100 MHz / 256 = 390 kHz\nwire pwm = (pcnt < duty);                       // duty 0..255\n|'],
  ['state machine (Verilog)', 'v', 'localparam IDLE = 2\'d0, RUN = 2\'d1, DONE = 2\'d2;\nreg [1:0] state = IDLE;\nalways @(posedge clk)\n    case (state)\n        IDLE: if (start) state <= RUN;\n        RUN:  if (finished) state <= DONE;\n        DONE: state <= IDLE;\n        default: state <= IDLE;\n    endcase\n|'],
  ['block RAM', 'v', 'reg [31:0] mem [0:1023];\nreg [31:0] q = 32\'d0;\nalways @(posedge clk) begin\n    if (we) mem[waddr] <= wdata;\n    q <= mem[raddr];                 // 1 clock latency\nend\n|'],
  ['shift register', 'v', 'reg [7:0] sr = 8\'d0;\nalways @(posedge clk) if (shift) sr <= {sr[6:0], din};\n|'],
  ['registers from C', 'c', '#include <fcntl.h>\n#include <sys/mman.h>\n#include <stdint.h>\nint fd = open("/dev/mem", O_RDWR | O_SYNC);\nvolatile uint32_t *r = mmap(0, 0x1000, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0x41200000);\nr[0] = 5;                    /* ctrl[0] */\nuint32_t s = r[0x80 / 4];    /* status[0] */\n|'],
];

// extra words for autocomplete
const CODE_WORDS = {
  ino: ['HIGH', 'LOW', 'INPUT', 'OUTPUT', 'INPUT_PULLUP', 'RISING', 'FALLING', 'CHANGE', 'MSBFIRST', 'LSBFIRST', 'LED_BUILTIN', 'A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6',
    'SCL', 'SDA', 'SCL1', 'SDA1', 'TP1', 'BUZZER', 'Serial', 'Serial1', 'Wire', 'Wire1', 'SPI', 'EEPROM', 'Servo', 'SPISettings', 'SPI_MODE0', 'SPI_MODE1', 'SPI_MODE2', 'SPI_MODE3',
    'void', 'int', 'long', 'unsigned', 'float', 'double', 'bool', 'byte', 'char', 'uint8_t', 'uint16_t', 'uint32_t', 'int32_t', 'const', 'static', 'volatile', 'return',
    'setup', 'loop', 'begin', 'println', 'print', 'available', 'read', 'write', 'attach', 'requestFrom', 'beginTransmission', 'endTransmission', 'transfer'],
  py: ['import', 'from', 'ardzy', 'MMIO', 'UIO', 'peek', 'poke', 'led', 'beep', 'button', 'fpga_state', 'time', 'sleep', 'monotonic', 'print', 'while', 'True', 'False', 'None',
    'range', 'len', 'def', 'class', 'return', 'struct', 'blocks', 'Bus'],
  v: ['module', 'endmodule', 'input', 'output', 'inout', 'wire', 'reg', 'assign', 'always', 'posedge', 'negedge', 'begin', 'end', 'if', 'else', 'case', 'endcase', 'default',
    'localparam', 'parameter', 'integer', 'generate', 'endgenerate', 'genvar', 'function', 'endfunction', 'clk', 'rstn', 'ctrl', 'status', 'leds', 'j1', 'j2', 'j3', 'j4', 'j5',
    'j6', 'j7', 'j8', 'j9', 'fan_pwm', 'fan_tach'],
  c: ['#include', 'stdint.h', 'stdio.h', 'fcntl.h', 'sys/mman.h', 'unistd.h', 'uint32_t', 'volatile', 'mmap', 'open', 'O_RDWR', 'O_SYNC', 'PROT_READ', 'PROT_WRITE', 'MAP_SHARED',
    'printf', 'usleep', 'return', 'static', 'const'],
};
