"""Makes pc_app/fpga/hdl/ardzy_radio_rom.v: the filter coefficients and the AM table of the FM radio block.

  LPF15   63-tap low-pass at 48828.125 Hz: passes 0..15 kHz, stops from 19 kHz (keeps the 19 kHz pilot clean)
  INTERP  96-tap interpolation filter (x8, 48828 -> 390625 samples/s): stops the images above 33.8 kHz
  ASIN    256 entries: AM envelope 0..1 -> pulse width (a 1-bit carrier's strength is sin(pi * width))
Kaiser-windowed sinc filters. Prints the measured response.
"""
import math, os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', '..', 'pc_app', 'fpga', 'hdl', 'ardzy_radio_rom.v'))


def bessel_i0(x):
    s, t, k = 1.0, 1.0, 1
    while t > 1e-12 * s:
        t *= (x / (2 * k)) ** 2
        s += t
        k += 1
    return s


def kaiser_lowpass(n, fc, fs, beta, gain=1.0):
    m = (n - 1) / 2
    h = []
    for i in range(n):
        x = i - m
        sinc = 2 * fc / fs if x == 0 else math.sin(2 * math.pi * fc / fs * x) / (math.pi * x)
        w = bessel_i0(beta * math.sqrt(1 - (x / m) ** 2)) / bessel_i0(beta)
        h.append(sinc * w)
    s = sum(h)
    return [v * gain / s for v in h]


def response(h, f, fs):
    re = sum(v * math.cos(2 * math.pi * f / fs * i) for i, v in enumerate(h))
    im = sum(v * math.sin(2 * math.pi * f / fs * i) for i, v in enumerate(h))
    return math.hypot(re, im)


def quant(h, frac):
    return [max(-131072, min(131071, round(v * (1 << frac)))) for v in h]


FS_A = 100e6 / 2048          # audio rate
FS_M = 100e6 / 256           # MPX rate
lpf = kaiser_lowpass(63, 17000, FS_A, 6.0)
itp = kaiser_lowpass(96, 24400, FS_M, 6.5, gain=8.0)
q_lpf, q_itp = quant(lpf, 17), quant(itp, 16)
print('LPF15 : 15 kHz %.2f dB, 17 kHz %.1f dB, 19 kHz %.1f dB, 24 kHz %.1f dB' % tuple(
    20 * math.log10(max(1e-9, response([v / 2 ** 17 for v in q_lpf], f, FS_A))) for f in (15000, 17000, 19000, 24000)))
print('INTERP: 15 kHz %.2f dB, 33.8 kHz %.1f dB, 48.8 kHz %.1f dB (gain 8 = 18.06 dB)' % tuple(
    20 * math.log10(max(1e-9, response([v / 2 ** 16 for v in q_itp], f, FS_M))) for f in (15000, 33800, 48828)))
asin = [round(1024 * math.asin(i / 255) / math.pi) for i in range(256)]

# SSB: a complex band-pass 300 .. 2700 Hz (a 1200 Hz low-pass moved up to 1500 Hz), gain 2: for a tone the
# output I + jQ is the tone itself at positive frequency only (the analytic signal). I alone = the band-pass.
lp = kaiser_lowpass(255, 1200, FS_A, 7.0)
c = 127
ssb_i = [2 * v * math.cos(2 * math.pi * 1500 * (k - c) / FS_A) for k, v in enumerate(lp)]
ssb_q = [2 * v * math.sin(2 * math.pi * 1500 * (k - c) / FS_A) for k, v in enumerate(lp)]
q_si, q_sq = quant(ssb_i, 17), quant(ssb_q, 17)


def cresp(f):
    w = 2 * math.pi * f / FS_A
    re = sum((a * math.cos(w * k) + b * math.sin(w * k)) for k, (a, b) in enumerate(zip(q_si, q_sq))) / 2 ** 17
    im = sum((b * math.cos(w * k) - a * math.sin(w * k)) for k, (a, b) in enumerate(zip(q_si, q_sq))) / 2 ** 17
    return 20 * math.log10(max(1e-9, math.hypot(re, im)))


print('SSB   : ' + ', '.join('%+d Hz %.1f dB' % (f, cresp(f)) for f in (300, 600, 1000, 2400, 2700, 3500, -300, -600, -1000, -2000)))

L = ['// Ardzy FPGA library: coefficient tables of ardzy_radio. GENERATED by fpga_projects/12_fm_radio/make_roms.py',
     '`timescale 1ns / 1ps',
     'module ardzy_radio_lpf15 (input wire clk, input wire [5:0] a, output reg signed [17:0] q = 18\'sd0);',
     '    reg [17:0] m [0:63];',
     '    initial begin']
L += ["        m[%d] = 18'h%05X;" % (i, v & 0x3FFFF) for i, v in enumerate(q_lpf + [0])]
L += ['    end', '    always @(posedge clk) q <= m[a];', 'endmodule', '',
      'module ardzy_radio_interp (input wire clk, input wire [6:0] a, output reg signed [17:0] q = 18\'sd0);',
      '    reg [17:0] m [0:127];', '    initial begin']
L += ["        m[%d] = 18'h%05X;" % (i, v & 0x3FFFF) for i, v in enumerate(q_itp + [0] * 32)]
L += ['    end', '    always @(posedge clk) q <= m[a];', 'endmodule', '',
      'module ardzy_radio_asin (input wire clk, input wire [7:0] a, output reg [9:0] q = 10\'d0);',
      '    reg [9:0] m [0:255];', '    initial begin']
L += ["        m[%d] = 10'd%d;" % (i, v) for i, v in enumerate(asin)]
L += ['    end', '    always @(posedge clk) q <= m[a];', 'endmodule', '']
for name, co in (('ardzy_radio_ssb_i', q_si), ('ardzy_radio_ssb_q', q_sq)):
    L += ["module %s (input wire clk, input wire [7:0] a, output reg signed [17:0] q = 18'sd0);" % name,
          '    (* rom_style = "block" *) reg [17:0] m [0:255];', '    initial begin']
    L += ["        m[%d] = 18'h%05X;" % (i, v & 0x3FFFF) for i, v in enumerate(co + [0])]
    L += ['    end', '    always @(posedge clk) q <= m[a];', 'endmodule', '']
open(OUT, 'w', newline='\n').write('\n'.join(L))
print('wrote', OUT)
