"""Ardzy FPGA projects: keep every project folder complete and consistent.

    python make_projects.py                 pins.xdc + blocks.py + guide.html for every project
    python make_projects.py --build [name]  also build the .bit with the built-in toolchain
    python make_projects.py --docs          also write Documents/06_FPGA_Projects.html

A project folder: project.json (title, pins, wiring, ...), top.v, main.py (demo), selftest.py,
panel.json (live controls in the Ardzy app), guide.md (the guide). Generated: pins.xdc, blocks.py
(copy of common/blocks.py), guide.html, <folder>.bit.
"""
import html, json, os, re, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.normpath(os.path.join(HERE, '..', 'pc_app'))
DOCS = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'Documents'))

# package pins of the S9 control board (from scripts/make_pins.py, checked on the board)
PINS = {
    'j1[0]': 'T11', 'j1[1]': 'T12', 'j1[2]': 'U12', 'j1[3]': 'T10',
    'j2[0]': 'R19', 'j2[1]': 'V12', 'j2[2]': 'W13', 'j2[3]': 'V13',
    'j3[0]': 'T14', 'j3[1]': 'P14', 'j3[2]': 'R14', 'j3[3]': 'T15',
    'j4[0]': 'Y16', 'j4[1]': 'W14', 'j4[2]': 'Y14', 'j4[3]': 'Y17',
    'j5[0]': 'T16', 'j5[1]': 'V15', 'j5[2]': 'W15', 'j5[3]': 'U17',
    'j6[0]': 'U14', 'j6[1]': 'U18', 'j6[2]': 'U19', 'j6[3]': 'U15',
    'j7[0]': 'T20', 'j7[1]': 'V20', 'j7[2]': 'W20', 'j7[3]': 'U20',
    'j8[0]': 'Y18', 'j8[1]': 'V16', 'j8[2]': 'W16', 'j8[3]': 'Y19',
    'j9[0]': 'R16', 'j9[1]': 'T17', 'j9[2]': 'R18', 'j9[3]': 'R17',
    'leds[0]': 'F16', 'leds[1]': 'L19', 'leds[2]': 'M19', 'leds[3]': 'M17', 'tp1': 'K18',
    'i2c1_scl': 'W18', 'i2c1_sda': 'W19', 'i2c2_scl': 'N17', 'i2c2_sda': 'P18',
    'fan_pwm': 'J18', 'fan_tach[0]': 'F19', 'fan_tach[1]': 'G18', 'fan_tach[2]': 'F20',
    'fan_tach[3]': 'J20', 'fan_tach[4]': 'G17', 'fan_tach[5]': 'H20',
}
CONNECTOR_PIN = {0: 5, 1: 11, 2: 12, 3: 15}         # jN[k] -> pin number on the 18-pin connector


def pin_label(name):
    m = re.fullmatch(r'j(\d)\[(\d)\]', name)
    if m:
        return 'J%s pin %d' % (m.group(1), CONNECTOR_PIN[int(m.group(2))])
    return {'i2c1_scl': 'SCL, J1..J8 pin 4', 'i2c1_sda': 'SDA, J1..J8 pin 3', 'i2c2_scl': 'SCL, J9 pin 4',
            'i2c2_sda': 'SDA, J9 pin 3'}.get(name, name)


def projects():
    return sorted(d for d in os.listdir(HERE) if re.match(r'\d\d_', d) and os.path.isfile(os.path.join(HERE, d, 'project.json')))


def load(name):
    return json.load(open(os.path.join(HERE, name, 'project.json'), encoding='utf-8'))


def write_xdc(name, p):
    lines = ['# Generated by fpga_projects/make_projects.py from project.json: edit the "pins" there.']
    for port, pin in p['pins'].items():
        if pin not in PINS:
            raise ValueError('%s: unknown board pin %s' % (name, pin))
        lines.append('set_property PACKAGE_PIN %s [get_ports {%s}]' % (PINS[pin], port))
        lines.append('set_property IOSTANDARD LVCMOS33 [get_ports {%s}]' % port)
        if pin.startswith(('j', 'i2c')) or port in p.get('pullup', []):
            lines.append('set_property PULLTYPE PULLUP [get_ports {%s}]' % port)
    # clocks made inside the FPGA (MMCM / PLL outputs): nextpnr does not work out their speed itself
    for net, mhz in p.get('clocks', {}).items():
        lines.append('create_clock -period %.3f [get_nets %s]' % (1000.0 / mhz, net))
    open(os.path.join(HERE, name, 'pins.xdc'), 'w', newline='\n').write('\n'.join(lines) + '\n')


# ---------------------------------------------------------------- a small Markdown -> HTML converter
def _inline(s):
    s = html.escape(s, quote=False)
    s = re.sub(r'`([^`]+)`', r'<code>\1</code>', s)
    s = re.sub(r'\*\*([^*]+)\*\*', r'<b>\1</b>', s)
    s = re.sub(r'(?<![\w*])\*([^*\n]+)\*(?![\w*])', r'<i>\1</i>', s)
    s = re.sub(r'\[([^\]]+)\]\((https?://[^)]+)\)', r'<a href="\2" target="_blank" rel="noopener">\1</a>', s)
    return s


def md_to_html(md):
    out, i, lines = [], 0, md.replace('\r\n', '\n').split('\n')
    while i < len(lines):
        l = lines[i]
        if l.startswith('```'):
            j = i + 1
            while j < len(lines) and not lines[j].startswith('```'):
                j += 1
            out.append('<pre><code>%s</code></pre>' % html.escape('\n'.join(lines[i + 1:j]), quote=False))
            i = j + 1
            continue
        if l.startswith(('<svg', '<figure', '<details')):                     # raw drawings, fold-out answers
            j = i
            end = '</svg>' if l.startswith('<svg') else '</figure>' if l.startswith('<figure') else '</details>'
            while j < len(lines) and end not in lines[j]:
                j += 1
            out.append('\n'.join(lines[i:j + 1]))
            i = j + 1
            continue
        m = re.match(r'(#{1,4}) (.*)', l)
        if m:
            n = len(m.group(1)) + 1
            out.append('<h%d>%s</h%d>' % (n, _inline(m.group(2)), n))
            i += 1
            continue
        if l.startswith('|'):
            rows = []
            while i < len(lines) and lines[i].startswith('|'):
                if not re.match(r'^\|[\s:|-]+\|$', lines[i]):
                    rows.append([c.strip() for c in lines[i].strip('|').split('|')])
                i += 1
            t = ['<table>', '<tr>%s</tr>' % ''.join('<th>%s</th>' % _inline(c) for c in rows[0])]
            t += ['<tr>%s</tr>' % ''.join('<td>%s</td>' % _inline(c) for c in r) for r in rows[1:]]
            out.append('\n'.join(t + ['</table>']))
            continue
        m = re.match(r'> \*\*(ok|info|warn|bad)\*\* (.*)', l)
        if m:
            body = [m.group(2)]
            i += 1
            while i < len(lines) and lines[i].startswith('> '):
                body.append(lines[i][2:])
                i += 1
            out.append('<div class="box %s">%s</div>' % (m.group(1), _inline(' '.join(body))))
            continue
        if re.match(r'(\d+\.|-) ', l):
            ordered = l[0].isdigit()
            items = []
            while i < len(lines) and re.match(r'(\d+\.|-) ', lines[i]):
                items.append(re.sub(r'^(\d+\.|-) ', '', lines[i]))
                i += 1
                while i < len(lines) and lines[i].startswith('   ') and lines[i].strip():
                    items[-1] += ' ' + lines[i].strip()
                    i += 1
            tag = 'ol' if ordered else 'ul'
            out.append('<%s>%s</%s>' % (tag, ''.join('<li>%s</li>' % _inline(x) for x in items), tag))
            continue
        if not l.strip():
            i += 1
            continue
        para = [l]
        i += 1
        while i < len(lines) and lines[i].strip() and not re.match(r'(#|\||```|> |\d+\. |- |<svg|<figure|<details)', lines[i]):
            para.append(lines[i])
            i += 1
        out.append('<p>%s</p>' % _inline(' '.join(para)))
    return '\n'.join(out)


def facts_html(name, p):
    rows = ['<tr><th>Slot</th><th>Address</th><th>Block</th></tr>']
    for s, what in p.get('slots', {}).items():
        lo, hi = (int(x) for x in s.split('-')) if '-' in s else (int(s), int(s))
        addr = '0x%08X' % (0x43C00000 + lo * 0x1000) + ('' if hi == lo else ' .. 0x%08X' % (0x43C00FFF + hi * 0x1000))
        rows.append('<tr><td>%s</td><td><code>%s</code></td><td>%s</td></tr>' % (s, addr, html.escape(what)))
    pins = ['<tr><th>Signal</th><th>Board pin</th><th>FPGA pin</th></tr>']
    for port, pin in p['pins'].items():
        if not port.startswith('leds['):
            pins.append('<tr><td><code>%s</code></td><td>%s</td><td>%s</td></tr>' % (html.escape(port), pin_label(pin), PINS[pin]))
    wiring = ''
    if p.get('wiring'):
        wiring = '<h3>Wiring</h3><table><tr><th>Board</th><th>Goes to</th><th>Note</th></tr>%s</table>' % ''.join(
            '<tr><td>%s</td><td>%s</td><td>%s</td></tr>' % tuple(html.escape(x) for x in w) for w in p['wiring'])
    parts = ''
    if p.get('parts'):
        parts = '<h3>Parts</h3><ul>%s</ul>' % ''.join('<li>%s</li>' % html.escape(x) for x in p['parts'])
    tested = ''
    if p.get('tested'):
        tested = '<div class="box ok"><b>Tested on the real board</b> %s</div>' % html.escape(p['tested'])
    return ('%s<h3>Registers (ARM side)</h3><table>%s</table><h3>Pins</h3><table>%s</table>%s%s'
            % (tested, ''.join(rows), ''.join(pins), wiring, parts))


def guide_html(name, p, standalone=True):
    md = open(os.path.join(HERE, name, 'guide.md'), encoding='utf-8').read()
    body = md_to_html(md)
    head = ('<div class="kicker">%s &middot; %s</div><h1>%s</h1><p class="lead">%s</p>'
            % (html.escape(p['category']), html.escape(p['level']), html.escape(p['title']), html.escape(p['summary'])))
    content = head + facts_html(name, p) + body
    if not standalone:
        return content
    return ('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">'
            '<title>%s</title><style>%s</style></head><body><main class="wrap">%s</main></body></html>'
            % (html.escape(p['title']), GUIDE_CSS, content))


GUIDE_CSS = '''
:root{--bg:#fbfaf7;--text:#1d2329;--muted:#5b6672;--line:#dfe3e8;--acc:#b8860b;--code:#f1f3f5;--ok:#e8f5e9;--info:#e8f1fb;--warn:#fff6e0;--bad:#fdecea}
@media (prefers-color-scheme: dark){:root{--bg:#15191d;--text:#e3e7eb;--muted:#9aa5b1;--line:#2c3339;--acc:#d4a84f;--code:#1f252b;--ok:#17301c;--info:#162638;--warn:#33290f;--bad:#3a1b18}}
body{margin:0;background:var(--bg);color:var(--text);font:15px/1.6 "Segoe UI",system-ui,sans-serif}
.wrap{max-width:900px;margin:0 auto;padding:16px 20px 40px}
h1{font-size:24px;margin:4px 0 6px}h2{font-size:19px;margin:26px 0 8px;border-bottom:1px solid var(--line);padding-bottom:4px}
h3{font-size:16px;margin:18px 0 6px}.kicker{color:var(--acc);font-size:12px;text-transform:uppercase;letter-spacing:.06em}
.lead{color:var(--muted);margin-top:0}code{background:var(--code);padding:1px 5px;border-radius:4px;font:13px Consolas,monospace}
pre{background:var(--code);padding:10px 12px;border-radius:8px;overflow:auto}pre code{padding:0;background:none}
table{border-collapse:collapse;width:100%;margin:6px 0 12px;font-size:14px;display:block;overflow-x:auto}
th,td{border:1px solid var(--line);padding:5px 8px;text-align:left;vertical-align:top}th{background:var(--code)}
.box{border-radius:8px;padding:9px 12px;margin:10px 0;border:1px solid var(--line)}.box.ok{background:var(--ok)}
.box.info{background:var(--info)}.box.warn{background:var(--warn)}.box.bad{background:var(--bad)}
svg{max-width:100%;height:auto}a{color:var(--acc)}
:root{--paper:#fff;--ps:#e8f1fb;--psl:#2f6db5;--pl:#eaf6ec;--pll:#2e8b57;--accs:#fbf1dc;--amb:#c58a00;--ambs:#fff3d6;--red:#c0392b;--reds:#fde8e6}
@media (prefers-color-scheme: dark){:root{--paper:#1b2026;--ps:#16263a;--psl:#6aa8f0;--pl:#15301f;--pll:#5cc98a;--accs:#33290f;--amb:#e3ad4c;--ambs:#33290f;--red:#ff7b7b;--reds:#3a1b18}}
figure{margin:16px 0 22px;border:1px solid var(--line);border-radius:10px;padding:12px;background:var(--paper)}
figure svg{width:100%;height:auto;display:block}figcaption{color:var(--muted);font-size:14px;margin-top:6px;text-align:center}
.d-text{fill:var(--text);font:14px "Segoe UI",sans-serif}.d-small{fill:var(--muted);font:12.5px "Segoe UI",sans-serif}
.d-title{fill:var(--text);font:600 15px "Segoe UI",sans-serif}.d-mono{fill:var(--text);font:12.5px Consolas,monospace}
.d-box{fill:var(--paper);stroke:var(--line);stroke-width:1.5}.d-ps{fill:var(--ps);stroke:var(--psl);stroke-width:1.5}
.d-pl{fill:var(--pl);stroke:var(--pll);stroke-width:1.5}.d-acc{fill:var(--accs);stroke:var(--acc);stroke-width:1.5}
.d-warn{fill:var(--ambs);stroke:var(--amb);stroke-width:1.5}.d-red{fill:var(--reds);stroke:var(--red);stroke-width:1.5}
.d-line{stroke:var(--muted);stroke-width:1.8;fill:none}.d-arrow{stroke:var(--acc);stroke-width:2.2;fill:none}
.d-blue{stroke:var(--psl);stroke-width:2.2;fill:none}.d-dash{stroke:var(--muted);stroke-width:1.5;fill:none;stroke-dasharray:5 4}
details{border:1px solid var(--line);border-radius:8px;padding:6px 12px;margin:8px 0}summary{cursor:pointer;font-weight:600}
'''


def write_guide(name, p):
    open(os.path.join(HERE, name, 'guide.html'), 'w', encoding='utf-8', newline='\n').write(guide_html(name, p))


def build(name):
    sys.path.insert(0, APP)
    from fpga import flow
    return flow.build(os.path.join(HERE, name), log=lambda s, c=None: print(s, flush=True), out_name=name)


def write_docs(names):
    cards, sections = [], []
    for n in names:
        p = load(n)
        cards.append('<a class="card" href="#%s"><span class="n">%s &middot; %s</span><h3>%s</h3><p>%s</p></a>'
                     % (n, html.escape(p['category']), html.escape(p['level']), html.escape(p['title']), html.escape(p['summary'])))
        sections.append('<section id="%s" class="project">%s<p><a href="#top">Back to the list</a></p></section>'
                        % (n, guide_html(n, p, standalone=False).replace('<h1>', '<h2>').replace('</h1>', '</h2>')))
    intro = open(os.path.join(HERE, 'docs_intro.html'), encoding='utf-8').read()
    page = ('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">'
            '<title>Ardzy FPGA Projects</title><link rel="stylesheet" href="docs.css"></head><body id="top">'
            '<header class="top"><div class="wrap"><nav class="back"><a href="index.html">&larr; All documents</a></nav>'
            '<div class="kicker">Document 6 &middot; Project 2_Ardzy</div><h1>FPGA projects: ready to upload</h1>'
            '<p>Every idea as a complete project: the design, a prebuilt bitstream, a demo, a self-test, live controls in the app and a guide.</p>'
            '</div></header><main class="wrap">%s<div class="cards">%s</div>%s</main></body></html>'
            % (intro, ''.join(cards), ''.join(sections)))
    open(os.path.join(DOCS, '06_FPGA_Projects.html'), 'w', encoding='utf-8', newline='\n').write(page)
    print('wrote', os.path.join(DOCS, '06_FPGA_Projects.html'))


def main():
    args = sys.argv[1:]
    names = [a for a in args if not a.startswith('--')]
    todo = [n for n in projects() if not names or n in names or any(n.startswith(x) for x in names)]
    for n in todo:
        p = load(n)
        write_xdc(n, p)
        shutil.copy(os.path.join(HERE, 'common', 'blocks.py'), os.path.join(HERE, n, 'blocks.py'))
        for f in p.get('extra_files', []):
            shutil.copy(os.path.join(HERE, 'common', f), os.path.join(HERE, n, f))
        if os.path.isfile(os.path.join(HERE, n, 'guide.md')):
            write_guide(n, p)
        print('%-20s %s' % (n, p['title']))
        if '--build' in args:
            build(n)
    if '--docs' in args:
        write_docs(projects())


if __name__ == '__main__':
    main()
